name: AMP_ASSv2 CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - test-workflow

jobs:
  build:
    strategy:
      fail-fast: false
    name: build-and-upload-ros-lib
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup ROS tooling
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: noetic
      - run: rosdep update
      - name: Install dependencies
        run: source /opt/ros/noetic/setup.sh && rosdep install --from-paths src -iry
      - name: Build packages
        run: source /opt/ros/noetic/setup.sh && catkin_make
      - name: Checkout ros_lib
        uses: actions/checkout@v3
        with:
          repository: Autonomous-Motorsports-Purdue/ros_lib
          path: ros_lib
      - run: rm -rf ros_lib/*
      - name: Build rosserial_arduino library
        run: |
          sudo apt install ros-noetic-rosserial-arduino
          source ./devel/setup.sh
          rosrun rosserial_arduino make_libraries.py dest
          mv dest/* ros_lib/
      - name: Commit changes to repo
        run: |
          cd ros_lib
          git config --global user.name AMP-Purdue
          git config --global user.email amppurdue@gmail.com
          git remote set-url origin https://github.com/Autonomous-Motorsports-Purdue/ros_lib.git
          git add -A
          git commit -m "Automated update (${{ github.sha }})"
          git push -u origin main

  build-cli:
    strategy:
      fail-fast: false
    name: build-cli
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Build amp-cli
        run: pip install .
