name: AMP_ASSv2 CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - test-workflow

jobs:
  build-test:
    strategy:
      fail-fast: false
    name: build-test-replacement
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup ROS tooling
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: noetic
      - run: rosdep update
      - name: Install dependencies
        run: source /opt/ros/noetic/setup.sh && rosdep install --from-paths src -iry
      - name: Build packages
        run: source /opt/ros/noetic/setup.sh && catkin_make

  build-cli:
    strategy:
      fail-fast: false
    name: build-cli
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Build amp-cli
        run: pip install .
