name: AMP_ASSv2 CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - test-workflow

jobs:
  build-test:
    strategy:
      fail-fast: false
    name: build-test-replacement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup ROS tooling
        uses: ros-tooling/setup-ros@v0.3
      - name: Generate deps.repos file
        run: |
          sudo apt install python3-rosinstall-generator &&
          rosinstall_generator serial_packet --rosdistro noetic \
          --deps-only --deps --upstream-development > /tmp/deps.repos
      - name: Build package
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: serial_packet
          target-ros1-distro: noetic
          vcs-repo-file-url: /tmp/deps.repos

  build-cli:
    strategy:
      fail-fast: false
    name: build-cli
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Build amp-cli
        run: pip install .
